Rails.application.routes.draw do
  get 'accueil/index'
  get 'register/new'
  get 'register/connexion'
  get 'personnage/new'
  get 'personnage/create'
  get 'gamemaster/new'
  get 'gamemaster/create'
  get 'gamemaster/index'
  get 'gamemaster/connexion'
  get 'gamemaster/deconnexion'
  get '/gamemaster/afficher/:id', to: 'gamemaster#show', as: 'gamemaster'
  get '/jeu/cinematic'
  get '/jeu/create'
  get '/jeu/play'
  get 'gamemaster/item'
  get 'gamemaster/createItem'
  get 'gamemaster/newItem'
  get 'gamemaster/pnj'
  get 'gamemaster/showItem'
  get 'gamemaster/giveItem'
  get 'gamemaster/giveItemUser'
  get 'gamemaster/editItem'
  get 'gamemaster/updateItem'
  get 'gamemaster/destroyItem'
  get 'gamemaster/createPnj'
  get 'gamemaster/newPnj'
  get 'gamemaster/showPnj'
  get 'gamemaster/erreurGiveItem'
  get 'gamemaster/createRequest'
  get 'gamemaster/newRequest'
  get 'gamemaster/showRequest'
  get 'gamemaster/request'
  get 'jeu/objetEquipe'
  get 'jeu/objetDesequipe'
  get 'jeu/objetSuppr'
  get 'jeu/objetSupprQuantite'
  get '/jeu/create_narration'
  get 'gamemaster/newCraft'
  get 'gamemaster/createCraft'
  get 'gamemaster/craft'
  get 'gamemaster/showCraft'
  get 'gamemaster/editCraft'
  get 'jeu/crafterLobjet'
  get 'jeu/narrationdeux'
  get 'jeu/combat'
  get 'jeu/recompenses'
  get 'gamemaster/editRequest'
  get 'jeu/requestCheck'
  get 'gamemaster/editPnj'
  get 'gamemaster/updatePnj'
  get 'jeu/lumina'


  post 'register/create'
  post 'register/connexion'
  post 'personnage/new'
  post 'personnage/create'
  post 'gamemaster/new'
  post 'gamemaster/create'
  post 'gamemaster/connexion'
  post 'jeu/cinematic'
  post 'jeu/create'
  post 'gamemaster/item'
  post 'gamemaster/createItem'
  post 'gamemaster/newItem'
  post 'gamemaster/giveItem'
  post 'gamemaster/editItem'
  post 'gamemaster/updateItem'
  post 'gamemaster/createPnj'
  post 'gamemaster/newPnj'
  post 'gamemaster/createRequest'
  post 'gamemaster/newRequest'
  post 'jeu/objetSupprQuantite'
  post '/jeu/create_narration'
  post 'gamemaster/newCraft'
  post 'gamemaster/createCraft'
  post 'gamemaster/updateCraft'
  post 'gamemaster/editRequest'

  
  delete 'register/destroy'
  delete 'gamemaster/afficher/:id', to: 'gamemaster#destroy', as: 'delete'
  delete 'gamemaster/deconnexion'
  delete 'gamemaster/destroyPnj'
  delete 'gamemaster/destroyItem'
  delete 'gamemaster/destroyRequest'
  delete 'jeu/supprObjetInventaire', to: 'jeu#supprObjetInventaire', as: 'jeu_supprObjetInventaire'
  delete 'gamemaster/destroyCraft'
  
  patch 'gamemaster/updateItem'
  patch 'gamemaster/updateCraft'
  patch 'gamemaster/updateRequest'
  patch 'gamemaster/updatePnj'

  root 'accueil#index'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
