Rails.application.routes.draw do
  get 'accueil/index'
  get 'register/new'
  get 'register/connexion'
  get 'personnage/new'
  get 'personnage/create'
  get 'gamemaster/new'
  get 'gamemaster/create'
  get 'gamemaster/index'
  get 'gamemaster/connexion'
  get 'gamemaster/deconnexion'
  get '/gamemaster/afficher/:id', to: 'gamemaster#show', as: 'gamemaster'
  get '/jeu/cinematic'
  get '/jeu/create'
  get '/jeu/play'
  get 'gamemaster/item'
  get 'gamemaster/createItem'
  get 'gamemaster/newItem'
  get 'gamemaster/pnj'
  get 'gamemaster/showItem'
  get 'gamemaster/giveItem'
  get 'gamemaster/giveItemUser'
  get 'gamemaster/editItem'
  get 'gamemaster/updateItem'
  get 'gamemaster/destroyItem'
  get 'gamemaster/createPnj'
  get 'gamemaster/newPnj'
  get 'gamemaster/showPnj'


  post 'register/create'
  post 'register/connexion'
  post 'personnage/new'
  post 'personnage/create'
  post 'gamemaster/new'
  post 'gamemaster/create'
  post 'gamemaster/connexion'
  post 'jeu/cinematic'
  post 'jeu/create'
  post 'gamemaster/item'
  post 'gamemaster/createItem'
  post 'gamemaster/newItem'
  post 'gamemaster/giveItem'
  post 'gamemaster/editItem'
  post 'gamemaster/updateItem'
  post 'gamemaster/createPnj'
  post 'gamemaster/newPnj'
  
  
  delete 'register/destroy'
  delete 'gamemaster/afficher/:id', to: 'gamemaster#destroy', as: 'delete'
  delete 'gamemaster/deconnexion'
  delete 'gamemaster/destroyPnj'
  delete 'gamemaster/destroyItem'
  
  patch 'gamemaster/updateItem'

  root 'accueil#index'

  get 'gamemaster/createRequest'
  get 'gamemaster/newRequest'
  get 'gamemaster/showRequest'
  get 'gamemaster/request'
post 'gamemaster/createRequest'
  post 'gamemaster/newRequest'
delete 'gamemaster/destroyRequest'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
